
// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-native.ts

/** @typedef {"modern" | "baseline" | "default"} EmbeddedAddonVariant */

/**
 * @typedef {Object} EmbeddedAddonFile
 * @property {EmbeddedAddonVariant} variant
 * @property {string} filename
 * @property {number} size
 * @property {string=} filePath
 */

/**
 * @typedef {Object} EmbeddedAddonArchive
 * @property {"tar.gz"} format
 * @property {string} filename
 * @property {string} filePath
 */

/**
 * @typedef {Object} EmbeddedAddon
 * @property {string} platformTag
 * @property {string} version
 * @property {EmbeddedAddonFile[]} files
 * @property {EmbeddedAddonArchive=} archive
 */

import archivePath from "../native/embedded-addons.linux-x64.tar.gz" with { type: "file" };

export const embeddedAddon = {
	platformTag: "linux-x64",
	version: "18.1.19",
	archive: {
		format: "tar.gz",
		filename: "embedded-addons.linux-x64.tar.gz",
		filePath: archivePath,
	},
	files: [
		{ variant: "modern", filename: "pi_natives.linux-x64-modern.node", size: 210397864 },
	],
};
