//! Configures the selected CPython runtime and packs the crate-provided Python
//! modules (`python/`) plus the pure-Python packages pinned in
//! `requirements.txt` into a frozen-modules blob.
//!
//! Native desktop builds use the python-build-standalone archive and emit its
//! dependency link inputs from `PYTHON.json`. Android/Termux uses the installed
//! GIL-enabled CPython shared library instead: no archive metadata or static
//! libpython is required there, while the system stdlib and `lib-dynload`
//! directories are passed to the isolated runtime explicitly.
//!
//! pyo3 configures itself from `PYO3_CONFIG_FILE` before this script runs; the
//! file therefore identifies the exact interpreter used both for linking and
//! for bytecode packing. The config file sits at the root of the generated
//! tree, so its parent directory is the vendor directory.

use std::{
	collections::BTreeSet,
	env,
	fmt::Write,
	fs,
	path::{Path, PathBuf},
	process::Command,
};

/// System libraries only `_tkinter` needs; it is not in the static inittab
/// (pbs ships it as a shared module), so its archive member is never pulled.
const TCL_LIBS: [&str; 2] = ["tcl9.0", "tcl9tk9.0"];

fn main() {
	let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
	let target_os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
	let is_android = target_os == "android";

	// pyo3-ffi configures itself from PYO3_CONFIG_FILE *before* this script
	// has any say; if it is unset or points elsewhere, pyo3 silently
	// introspects a host Python and links the wrong runtime. This repo's
	// .cargo/config.toml sets it for workspace members; external consumers
	// must set it themselves (environment or their own `[env]` section).
	println!("cargo::rerun-if-env-changed=PYO3_CONFIG_FILE");
	let config_path = env::var_os("PYO3_CONFIG_FILE").map(PathBuf::from);
	let config = config_path
		.as_ref()
		.and_then(|p| {
			p.canonicalize()
				.ok()
				.or_else(|| manifest.join("../..").join(p).canonicalize().ok())
		})
		.unwrap_or_else(|| {
			panic!(
				"PYO3_CONFIG_FILE (got {config_path:?}) must point at an existing pyo3-config.txt \
				 generated by omp-py's scripts/fetch-python.sh; run crates/py/scripts/fetch-python.sh \
				 first"
			)
		});
	let vendor = config
		.parent()
		.expect("PYO3_CONFIG_FILE has no parent directory")
		.to_path_buf();
	println!("cargo::rerun-if-changed={}", config.display());

	if is_android {
		validate_android_config(&config);
	} else {
		assert!(
			vendor.join("PYTHON.json").is_file(),
			"{} does not sit in a python-build-standalone vendor tree — run omp-py's \
			 scripts/fetch-python.sh first",
			config.display()
		);
		println!("cargo::rerun-if-changed={}", vendor.join("PYTHON.json").display());
		println!("cargo::rerun-if-changed={}", vendor.join("stdlib.bin").display());
	}

	// macOS's `@available` checks require compiler-rt because rustc links with
	// `-nodefaultlibs`; Linux archives do not ship or reference this Darwin
	// runtime. Android links the system shared library through pyo3's config
	// and has no vendored static archives to enumerate.
	let mut static_libs = BTreeSet::new();
	let mut frameworks = BTreeSet::new();
	let mut system_libs = BTreeSet::new();
	if !is_android {
		let json: serde_json::Value =
			serde_json::from_str(&std::fs::read_to_string(vendor.join("PYTHON.json")).unwrap())
				.unwrap();
		if target_os == "macos" {
			static_libs.insert("clang_rt.osx".to_owned());
		}
		let extensions = json["build_info"]["extensions"].as_object().unwrap();
		for variant in extensions.values().flat_map(|v| v.as_array().unwrap()) {
			for link in variant["links"].as_array().unwrap() {
				let name = link["name"].as_str().unwrap();
				if link["path_static"].is_string() {
					static_libs.insert(name.to_owned());
				} else if link["framework"].as_bool() == Some(true) {
					frameworks.insert(name.to_owned());
				} else if !TCL_LIBS.contains(&name) {
					system_libs.insert(name.to_owned());
				}
			}
		}
	}

	// The release vendored archive contains LLVM-22 LTO bitcode, which Xcode's
	// ld64 cannot read; scripts/ld64.lld routes the link through a matching
	// Homebrew lld. Dev trees (freethreaded+debug) use native machine code and
	// skip the shim entirely. Gated by the `needs-lld` marker dropped by
	// fetch-python.sh.
	// A missing marker is deliberately NOT tracked: cargo treats a missing
	// `rerun-if-changed` path as always changed, which would rebuild omp-py
	// (and relink every dependent binary) on each invocation. Marker
	// appearance is covered by the tracked PYTHON.json, which fetch-python.sh
	// rewrites whenever it regenerates the vendor tree.
	let needs_lld = !is_android && vendor.join("needs-lld").is_file();
	if needs_lld {
		println!("cargo::rerun-if-changed={}", vendor.join("needs-lld").display());
		let shim = manifest.join("scripts/ld64.lld");
		assert!(
			shim.is_file(),
			"this Python tree requires omp-py's ld64.lld shim at {}; restore \
			 crates/py/scripts/ld64.lld",
			shim.display()
		);
		println!("cargo::rustc-link-arg=--ld-path={}", shim.display());
	}

	// Wheels' native extensions resolve CPython symbols from this executable
	// at dlopen; keep every global (code AND data like PyExc_*) through
	// dead-strip so the full C-API surface stays exported. ld64 and ELF linkers
	// spell this flag differently; passing ld64's spelling to an ELF linker is
	// parsed as `-e xport_dynamic`, producing no valid entry point. Other object
	// formats have no compatible flag.
	let target_vendor = env::var("CARGO_CFG_TARGET_VENDOR").unwrap_or_default();
	let target_family = env::var("CARGO_CFG_TARGET_FAMILY").unwrap_or_default();
	let link_arg = if target_vendor == "apple" {
		Some("-Wl,-export_dynamic")
	} else if target_os != "aix" && target_family.split(',').any(|family| family == "unix") {
		Some("-Wl,--export-dynamic")
	} else {
		None
	};
	if let Some(link_arg) = link_arg {
		println!("cargo::rustc-link-arg={link_arg}");
	}

	if !is_android {
		// Static archives propagate transitively: they bundle into this crate's
		// rlib and reach any downstream binary. Unreferenced members cost
		// nothing — they are only pulled when they resolve a symbol.
		println!("cargo::rustc-link-search=native={}", vendor.join("build/lib").display());
		for lib in &static_libs {
			println!("cargo::rustc-link-lib=static={lib}");
		}
		for framework in &frameworks {
			println!("cargo::rustc-link-lib=framework={framework}");
		}
		for lib in &system_libs {
			println!("cargo::rustc-link-lib={lib}");
		}
	}
	// Crate-provided Python modules (omp_remote, ...) and the pure-Python
	// packages pinned in requirements.txt are marshalled by the configured
	// interpreter. This keeps the bytecode format aligned with the runtime on
	// both the vendored desktop and system Android backends.
	let py_src = manifest.join("python");
	let requirements = manifest.join("requirements.txt");
	let packer = manifest.join("scripts/pack-pymodules.py");
	println!("cargo::rerun-if-changed={}", py_src.display());
	println!("cargo::rerun-if-changed={}", requirements.display());
	println!("cargo::rerun-if-changed={}", packer.display());
	let frozen_metadata =
		PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("frozen_distributions.rs");
	write_frozen_distributions(&requirements, &frozen_metadata);
	println!("cargo::rustc-env=OMP_PY_FROZEN_DISTRIBUTIONS={}", frozen_metadata.display());

	let url_vocab = manifest.join("../tools/url-vocab.json");
	println!("cargo::rerun-if-changed={}", url_vocab.display());
	let frozen_generated = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("frozen-python");
	fs::create_dir_all(&frozen_generated).expect("create generated frozen-module directory");
	let vocabulary: serde_json::Value =
		serde_json::from_str(&fs::read_to_string(&url_vocab).expect("read canonical URL vocabulary"))
			.expect("parse canonical URL vocabulary");
	let mut vocabulary_module =
		String::from("\"\"\"Generated canonical URL and selector vocabulary; do not edit.\"\"\"\n");
	writeln!(
		&mut vocabulary_module,
		"URL_VOCAB_VERSION = {}\nSELECTOR_GRAMMAR = {}\nSCHEMES = (",
		vocabulary["version"]
			.as_u64()
			.expect("URL vocabulary version"),
		serde_json::to_string(
			vocabulary["selector_grammar"]
				.as_str()
				.expect("URL selector grammar"),
		)
		.expect("serialize selector grammar"),
	)
	.expect("write URL vocabulary header");
	for scheme in vocabulary["schemes"].as_array().expect("URL scheme rows") {
		let member = scheme["member"].as_str().expect("URL scheme member");
		let wire = scheme["wire"]
			.as_array()
			.expect("URL scheme wire spellings");
		let selectors = scheme["selectors"].as_bool().expect("URL selector support");
		let mut wire_values = wire
			.iter()
			.map(|value| serde_json::to_string(value.as_str().expect("URL wire spelling")))
			.collect::<Result<Vec<_>, _>>()
			.expect("serialize URL wire spellings")
			.join(", ");
		if wire.len() == 1 {
			wire_values.push(',');
		}
		writeln!(
			&mut vocabulary_module,
			"    ({}, ({}), {}),",
			serde_json::to_string(member).expect("serialize URL member"),
			wire_values,
			if selectors { "True" } else { "False" },
		)
		.expect("write URL vocabulary scheme");
	}
	vocabulary_module.push_str(")\n");
	fs::write(frozen_generated.join("_omp_url_vocab.py"), vocabulary_module)
		.expect("write generated frozen URL vocabulary");

	let interpreter = if is_android {
		configured_interpreter(&config)
	} else {
		["python3.14td", "python3.14t"]
			.iter()
			.map(|name| vendor.join("install/bin").join(name))
			.find(|p| p.is_file())
			.expect("vendored interpreter missing — run omp-py's scripts/fetch-python.sh first")
	};
	let bundled = bundled_packages(&requirements, &vendor);
	let modules_blob = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("omp_modules.bin");
	let mut pack = Command::new(&interpreter);
	pack.arg(&packer).arg(&py_src);
	pack.arg(&frozen_generated);
	if let Some(dir) = &bundled {
		pack.arg(dir);
	}
	let status = pack
		.arg(&modules_blob)
		.args(["--prefix", "<omp-py>"])
		.args(["--exclude", "*.dist-info", "__pycache__", "bin"])
		.status()
		.expect("failed to run pack-pymodules.py");
	assert!(status.success(), "pack-pymodules.py failed");

	if is_android {
		let [stdlib, dynload, system_site, bundled] = android_runtime_paths(&interpreter, &vendor);
		println!("cargo::rustc-env=OMP_PY_STDLIB_PATH={}", stdlib.display());
		println!("cargo::rustc-env=OMP_PY_DYNLOAD_PATH={}", dynload.display());
		println!("cargo::rustc-env=OMP_PY_SYSTEM_SITE={}", system_site.display());
		println!("cargo::rustc-env=OMP_PY_BUNDLED_SITE={}", bundled.display());
	} else {
		println!("cargo::rustc-env=OMP_STDLIB_BLOB={}", vendor.join("stdlib.bin").display());
	}
	println!("cargo::rustc-env=OMP_PY_MODULES_BLOB={}", modules_blob.display());
}

fn config_value(config: &Path, key: &str) -> Option<String> {
	std::fs::read_to_string(config)
		.expect("read PYO3_CONFIG_FILE")
		.lines()
		.find_map(|line| line.strip_prefix(key)?.strip_prefix('='))
		.map(str::trim)
		.filter(|value| !value.is_empty())
		.map(str::to_owned)
}

fn validate_android_config(config: &Path) {
	assert_eq!(
		config_value(config, "implementation").as_deref(),
		Some("CPython"),
		"Android omp-py requires a CPython PYO3_CONFIG_FILE"
	);
	assert_eq!(
		config_value(config, "version").as_deref(),
		Some("3.14"),
		"Android omp-py requires system CPython 3.14"
	);
	assert_eq!(
		config_value(config, "shared").as_deref(),
		Some("true"),
		"Android omp-py requires a shared system libpython"
	);
	assert_eq!(
		config_value(config, "abi3").as_deref(),
		Some("false"),
		"Android omp-py does not use the stable or free-threaded ABI"
	);
	let flags = config_value(config, "build_flags").unwrap_or_default();
	assert!(
		!flags
			.split(',')
			.any(|flag| flag.trim() == "Py_GIL_DISABLED"),
		"Android omp-py requires the GIL-enabled CPython build"
	);
	let library = config_value(config, "lib_name").expect("Android PYO3 config has no lib_name");
	assert!(
		library.starts_with("python3.14") && !library.ends_with('t'),
		"Android omp-py requires the CPython 3.14 shared library, got {library:?}"
	);
	assert!(config_value(config, "lib_dir").is_some(), "Android PYO3 config has no lib_dir");
	assert!(config_value(config, "executable").is_some(), "Android PYO3 config has no executable");
}

fn configured_interpreter(config: &Path) -> PathBuf {
	let executable = PathBuf::from(
		config_value(config, "executable").expect("Android PYO3 config has no executable"),
	);
	assert!(
		executable.is_file(),
		"Android CPython executable {} is missing — run omp-py's setup-python",
		executable.display()
	);
	executable
}

fn android_runtime_paths(interpreter: &Path, vendor: &Path) -> [PathBuf; 4] {
	let paths_file = vendor.join("python-paths.env");
	println!("cargo::rerun-if-changed={}", paths_file.display());
	let (stdlib, dynload, system_site) = if paths_file.is_file() {
		let contents =
			std::fs::read_to_string(&paths_file).expect("read Android Python runtime paths");
		let values = contents
			.lines()
			.filter_map(|line| line.split_once('='))
			.collect::<std::collections::BTreeMap<_, _>>();
		(
			PathBuf::from(
				values
					.get("OMP_PY_STDLIB_PATH")
					.expect("Android Python paths missing OMP_PY_STDLIB_PATH"),
			),
			PathBuf::from(
				values
					.get("OMP_PY_DYNLOAD_PATH")
					.expect("Android Python paths missing OMP_PY_DYNLOAD_PATH"),
			),
			PathBuf::from(
				values
					.get("OMP_PY_SYSTEM_SITE")
					.expect("Android Python paths missing OMP_PY_SYSTEM_SITE"),
			),
		)
	} else {
		let output = Command::new(interpreter)
			.args([
				"-c",
				"import pathlib, sysconfig; stdlib = sysconfig.get_path('stdlib'); dynload = \
				 sysconfig.get_config_var('DESTSHARED') or str(pathlib.Path(stdlib) / 'lib-dynload'); \
				 system_site = sysconfig.get_path('purelib'); print(stdlib); print(dynload); \
				 print(system_site)",
			])
			.output()
			.expect("query Android CPython runtime paths");
		assert!(output.status.success(), "Android CPython rejected its sysconfig path query");
		let stdout =
			String::from_utf8(output.stdout).expect("Android CPython emitted non-UTF-8 runtime paths");
		let mut lines = stdout.lines().map(PathBuf::from);
		(
			lines.next().expect("Android CPython omitted stdlib path"),
			lines
				.next()
				.expect("Android CPython omitted lib-dynload path"),
			lines
				.next()
				.expect("Android CPython omitted system site path"),
		)
	};
	assert!(stdlib.is_dir(), "Android CPython stdlib {} is missing", stdlib.display());
	assert!(dynload.is_dir(), "Android CPython lib-dynload {} is missing", dynload.display());
	assert!(
		system_site.is_dir(),
		"Android CPython system site {} is missing",
		system_site.display()
	);
	[stdlib, dynload, system_site, vendor.join("bundled")]
}

/// Locates the bundled third-party packages (pinned in `requirements.txt`,
/// fetched by scripts/fetch-python.sh into `vendor/python/bundled`), or
/// `None` when the manifest lists nothing. Build time does no network I/O
/// and never writes outside `OUT_DIR`: this only checks that the cached
/// tree's stamp matches the manifest text and fails with a pointer to the
/// fetch script when it is missing or stale.
fn bundled_packages(requirements: &Path, vendor: &Path) -> Option<PathBuf> {
	let spec = fs::read_to_string(requirements).unwrap_or_default();
	let listed = spec
		.lines()
		.map(str::trim)
		.any(|l| !l.is_empty() && !l.starts_with('#'));
	if !listed {
		return None;
	}
	let dir = vendor.join("bundled");
	let stamp = dir.join(".requirements.stamp");
	println!("cargo::rerun-if-changed={}", stamp.display());
	assert!(
		std::fs::read_to_string(&stamp).ok().as_deref() == Some(&spec),
		"bundled packages under {} missing or stale vs {} — run omp-py's scripts/fetch-python.sh",
		dir.display(),
		requirements.display()
	);
	Some(dir)
}

/// Emits the frozen distribution metadata consumed by the extension resolver.
///
/// Requirements are intentionally parsed narrowly: bundled distributions must
/// be exact pins, while one or more `--hash=sha256:` entries may follow the
/// pin for `uv --require-hashes`.
fn write_frozen_distributions(requirements: &Path, output: &Path) {
	let requirements = fs::read_to_string(requirements).expect("read frozen Python requirements");
	let mut rows = Vec::new();
	for line in requirements.lines().map(str::trim) {
		if line.is_empty() || line.starts_with('#') {
			continue;
		}
		let pin = line
			.split_whitespace()
			.next()
			.expect("nonempty requirement");
		let (name, version) = pin
			.split_once("==")
			.filter(|(_, version)| !version.is_empty())
			.unwrap_or_else(|| panic!("frozen requirement must use name==version: {line}"));
		rows.push((name, version));
	}
	let mut source = String::from(
		"/// Frozen third-party distributions compiled into the embedded runtime.\nconst \
		 FROZEN_DISTRIBUTIONS: &[(&str, &str)] = &[\n",
	);
	for (name, version) in rows {
		writeln!(&mut source, "\t({name:?}, {version:?}),").expect("write frozen metadata");
	}
	source.push_str("];\n");
	fs::write(output, source).expect("write frozen distribution metadata");
}
