import type { ModelSpec } from "../types";
import { Effort } from "../effort";

export const GROKBOT_BACKEND = "https://api2.cursor.sh";
export const GROKBOT_API = "grokbot-sand" as const;
export const GROKBOT_DEFAULT_MODEL_ID = "sand-default";

/**
 * Metering is intentionally $0: sand usage is billed on the renewer account,
 * not as omp-side token pricing. Stats/usage surfaces will show zero cost.
 */
const COST = { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 } as const;

/** Sand InferenceService effort ladder (maps max→xhigh on the wire). */
const GROKBOT_THINKING = {
	mode: "effort" as const,
	efforts: [Effort.Minimal, Effort.Low, Effort.Medium, Effort.High, Effort.XHigh],
};

type GrokbotModelSeed = {
	id: string;
	name: string;
	reasoning: boolean;
};

/** Grok Bot model aliases for `grokbot` (not `cursor`, not `xai` / Grok CLI). */
export const GROKBOT_MODEL_SEEDS: readonly GrokbotModelSeed[] = [
	{ id: "default", name: "Auto", reasoning: false },
	{ id: "auto", name: "auto", reasoning: false },
	{ id: "grok-4.6", name: "Grok 4.6 (sand)", reasoning: true },
	{ id: "composer-2.5", name: "Composer 2.5", reasoning: true },
	{ id: "composer-latest", name: "composer-latest", reasoning: true },
	{ id: "composer", name: "composer", reasoning: true },
	{ id: "composer-2-5", name: "composer-2-5", reasoning: true },
	{ id: "claude-opus-5", name: "Claude Opus 5", reasoning: true },
	{ id: "opus-latest", name: "opus-latest", reasoning: true },
	{ id: "opus", name: "opus", reasoning: true },
	{ id: "opus-5", name: "opus-5", reasoning: true },
	{ id: "claude-opus-4-8", name: "Claude Opus 4.8", reasoning: true },
	{ id: "opus-4.8", name: "opus-4.8", reasoning: true },
	{ id: "opus-4-8", name: "opus-4-8", reasoning: true },
	{ id: "gpt-5.6-sol", name: "GPT-5.6 Sol", reasoning: true },
	{ id: "gpt-latest", name: "gpt-latest", reasoning: true },
	{ id: "gpt", name: "gpt", reasoning: true },
	{ id: "gpt-5-6-sol", name: "gpt-5-6-sol", reasoning: true },
	{ id: "gpt-5.6", name: "gpt-5.6", reasoning: true },
	{ id: "gpt-5.5", name: "GPT-5.5", reasoning: true },
	{ id: "gpt-5-5", name: "gpt-5-5", reasoning: true },
	{ id: "claude-fable-5", name: "Claude Fable 5", reasoning: true },
	{ id: "fable", name: "fable", reasoning: true },
	{ id: "fable-5", name: "fable-5", reasoning: true },
	{ id: "grok-4.5", name: "Grok 4.5 (sand)", reasoning: true },
	{ id: "gemini-3.7-flash", name: "Gemini 3.7 Flash", reasoning: true },
	{ id: "gemini-flash-latest", name: "gemini-flash-latest", reasoning: true },
	{ id: "gemini-flash", name: "gemini-flash", reasoning: true },
	{ id: "gpt-5.6-terra", name: "GPT-5.6 Terra", reasoning: true },
	{ id: "gpt-5-6-terra", name: "gpt-5-6-terra", reasoning: true },
	{ id: "claude-sonnet-5", name: "Claude Sonnet 5", reasoning: true },
	{ id: "sonnet-latest", name: "sonnet-latest", reasoning: true },
	{ id: "sonnet-5", name: "sonnet-5", reasoning: true },
	{ id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6", reasoning: true },
	{ id: "sonnet", name: "sonnet", reasoning: true },
	{ id: "sonnet-4.6", name: "sonnet-4.6", reasoning: true },
	{ id: "sonnet-4-6", name: "sonnet-4-6", reasoning: true },
	{ id: "gpt-5.3-codex", name: "Codex 5.3", reasoning: true },
	{ id: "codex-latest", name: "codex-latest", reasoning: true },
	{ id: "codex", name: "codex", reasoning: true },
	{ id: "codex-5.3", name: "codex-5.3", reasoning: true },
	{ id: "claude-opus-4-7", name: "Claude Opus 4.7", reasoning: true },
	{ id: "opus-4.7", name: "opus-4.7", reasoning: true },
	{ id: "opus-4-7", name: "opus-4-7", reasoning: true },
	{ id: "gpt-5.4", name: "GPT-5.4", reasoning: true },
	{ id: "claude-opus-4-6", name: "Claude Opus 4.6", reasoning: true },
	{ id: "opus-4.6", name: "opus-4.6", reasoning: true },
	{ id: "opus-4-6", name: "opus-4-6", reasoning: true },
	{ id: "claude-opus-4-5", name: "Claude Opus 4.5", reasoning: true },
	{ id: "opus-4.5", name: "opus-4.5", reasoning: true },
	{ id: "opus-4-5", name: "opus-4-5", reasoning: true },
	{ id: "gpt-5.2", name: "GPT-5.2", reasoning: true },
	{ id: "gpt-5.6-luna", name: "GPT-5.6 Luna", reasoning: true },
	{ id: "gpt-5-6-luna", name: "gpt-5-6-luna", reasoning: true },
	{ id: "gemini-3.6-flash", name: "Gemini 3.6 Flash", reasoning: true },
	{ id: "gemini-3.1-pro", name: "Gemini 3.1 Pro", reasoning: true },
	{ id: "gemini-latest", name: "gemini-latest", reasoning: true },
	{ id: "gemini-pro-latest", name: "gemini-pro-latest", reasoning: true },
	{ id: "gemini", name: "gemini", reasoning: true },
	{ id: "gemini-pro", name: "gemini-pro", reasoning: true },
	{ id: "gpt-5.4-mini", name: "GPT-5.4 Mini", reasoning: true },
	{ id: "gpt-mini-latest", name: "gpt-mini-latest", reasoning: true },
	{ id: "gpt-mini", name: "gpt-mini", reasoning: true },
	{ id: "gpt-5.4-nano", name: "GPT-5.4 Nano", reasoning: true },
	{ id: "gpt-nano-latest", name: "gpt-nano-latest", reasoning: true },
	{ id: "gpt-nano", name: "gpt-nano", reasoning: true },
	{ id: "claude-haiku-4-5", name: "Claude Haiku 4.5", reasoning: true },
	{ id: "haiku-latest", name: "haiku-latest", reasoning: true },
	{ id: "haiku", name: "haiku", reasoning: true },
	{ id: "haiku-4.5", name: "haiku-4.5", reasoning: true },
	{ id: "haiku-4-5", name: "haiku-4-5", reasoning: true },
	{ id: "claude-sonnet-4-5", name: "Claude Sonnet 4.5", reasoning: true },
	{ id: "sonnet-4.5", name: "sonnet-4.5", reasoning: true },
	{ id: "sonnet-4-5", name: "sonnet-4-5", reasoning: true },
	{ id: "gpt-5.1", name: "GPT-5.1", reasoning: true },
	{ id: "gemini-3-flash", name: "Gemini 3 Flash", reasoning: true },
	{ id: "gemini-3.5-flash", name: "Gemini 3.5 Flash", reasoning: true },
	{ id: "claude-sonnet-4", name: "Claude Sonnet 4", reasoning: true },
	{ id: "sonnet-4", name: "sonnet-4", reasoning: true },
	{ id: "gpt-5-mini", name: "GPT-5 Mini", reasoning: true },
	{ id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", reasoning: true },
	{ id: "kimi-k3", name: "Kimi K3", reasoning: true },
	{ id: "kimi-k2.7-code", name: "Kimi K2.7 Code", reasoning: true },
	{ id: "kimi-latest", name: "kimi-latest", reasoning: true },
	{ id: "kimi", name: "kimi", reasoning: true },
	{ id: "glm-5.2", name: "GLM 5.2", reasoning: true },
	{ id: "sand-default", name: "sand-default (routed)", reasoning: true },
	{ id: "sand-cua", name: "sand-cua (routed)", reasoning: false },
	{ id: "sand-automation", name: "sand-automation (routed)", reasoning: false },
	{ id: "sand-mock", name: "sand-mock", reasoning: false },
	{ id: "grok-4.5-medium", name: "deprecated grok-4.5-medium", reasoning: true },
	{ id: "grok-4.5-fast-medium", name: "deprecated grok-4.5-fast-medium", reasoning: true },
	{ id: "grok-4.5-high", name: "deprecated grok-4.5-high", reasoning: true },
	{ id: "grok-4.5-fast-high", name: "deprecated grok-4.5-fast-high", reasoning: true },
	{ id: "grok-4.5-xhigh", name: "deprecated grok-4.5-xhigh", reasoning: true },
	{ id: "grok-4.5-fast-xhigh", name: "deprecated grok-4.5-fast-xhigh", reasoning: true },
	{ id: "cursor-grok-4.5", name: "cursor-grok-4.5", reasoning: true },
	{ id: "cursor-grok-4.5-high-fast", name: "cursor-grok-4.5-high-fast", reasoning: true },
	{ id: "cursor-grok-4.5-high", name: "cursor-grok-4.5-high", reasoning: true },
	{ id: "vega", name: "vega", reasoning: true },
	{ id: "v9", name: "v9", reasoning: true },
	{ id: "composer-2.5-fast", name: "Composer 2.5 Fast", reasoning: true },
	{ id: "gpt-5.5-high-fast", name: "gpt-5.5-high-fast", reasoning: true },
	{ id: "premium", name: "premium (routed)", reasoning: false },
	{ id: "auto-low", name: "auto-low (routed)", reasoning: false },
	{ id: "auto-medium", name: "auto-medium (routed)", reasoning: false },
	{ id: "auto-high", name: "auto-high (routed)", reasoning: false },
	{ id: "auto-smart", name: "auto-smart (routed)", reasoning: false },
	{ id: "claude-sonnet-5-thinking-high", name: "claude-sonnet-5-thinking-high", reasoning: true },
	{ id: "claude-4.5-sonnet", name: "claude-4.5-sonnet", reasoning: true },
	{ id: "claude-4.5-opus-high", name: "claude-4.5-opus-high", reasoning: true },
];

export function buildGrokbotStaticSeed(baseUrl = GROKBOT_BACKEND): ModelSpec<"grokbot-sand">[] {
	return GROKBOT_MODEL_SEEDS.map(seed => ({
		id: seed.id,
		name: seed.name,
		api: GROKBOT_API,
		provider: "grokbot",
		baseUrl,
		reasoning: seed.reasoning,
		...(seed.reasoning ? { thinking: { ...GROKBOT_THINKING } } : {}),
		input: ["text", "image"],
		cost: COST,
		contextWindow: 200_000,
		maxTokens: 64_000,
		supportsTools: true,
	}));
}
