//! Curated isometric city for oh-my-pk.
//!
//! Layout is authored, not force-directed. Counts and packet payloads are
//! overwritten by `scan` so the map stays spatially stable while remaining
//! factually live.

use crate::model::{Box3, Child, Edge, EdgeKind, Graph, Metrics, Node, Section};

pub fn seed_city() -> Graph {
    let nodes = vec![
        // ── THE WORLD (rear-left inbound) ────────────────────────────────
        node(
            "providers",
            'W',
            "Providers",
            Section::World,
            "Remote model APIs. Anthropic, OpenAI, Gemini, Azure, Bedrock, Vertex, Ollama, Cursor, Codex, Devin. Tokens enter here.",
            "packages/ai/src/providers + register-builtins.ts. Heavy SDKs load lazily so CLI startup skips AWS/Google protobuf.",
            &[
                "packages/ai/src/providers",
                "packages/ai/src/providers/register-builtins.ts",
            ],
            vec![
                child("W1", "Anthropic", 1, "Messages + thinking + metadata"),
                child("W2", "OpenAI family", 3, "completions / responses / Codex"),
                child("W3", "Cloud", 4, "Azure, Bedrock, Vertex, Gemini"),
            ],
            Box3::new(-18.0, 10.0, 0.0, 5.0, 4.0, 3.2),
            vec![Box3::new(-17.2, 10.6, 3.2, 1.6, 1.4, 1.1)],
        ),
        node(
            "mcp",
            'M',
            "MCP Servers",
            Section::World,
            "External tool servers connected at boot. Exposed as mcp__* tools with a reconnect circuit-breaker (5 / 30s).",
            "packages/coding-agent/src/mcp/manager.ts. Subscriptions recover after drop. Discovery also reads .mcp.json.",
            &["packages/coding-agent/src/mcp"],
            vec![
                child("M1", "Manager", 1, "MCPManager connect / list / call"),
                child("M2", "Tools", 0, "{mcp} live mcp__* tools"),
            ],
            Box3::new(-18.0, 4.0, 0.0, 5.0, 4.0, 2.6),
            vec![],
        ),
        node(
            "workspace",
            'F',
            "Workspace",
            Section::World,
            "The cwd the agent is allowed to touch. Read/edit/bash/glob land here. Ethereal mode is a copy-on-write overlay.",
            "tools/read.ts, tools/edit, tools/bash.ts, tools/glob.ts. Path policy + hashline anchors live in the host.",
            &[
                "packages/coding-agent/src/tools/read.ts",
                "packages/coding-agent/src/tools/edit",
                "packages/coding-agent/src/tools/bash.ts",
            ],
            vec![
                child("F1", "Files", 0, "{ts} TypeScript sources"),
                child("F2", "Ethereal", 1, "copy-on-write cwd overlay"),
            ],
            Box3::new(-18.0, -2.0, 0.0, 5.0, 4.0, 2.4),
            vec![],
        ),
        node(
            "collab-world",
            'K',
            "Collab Guests",
            Section::World,
            "Browser guests and the Cloudflare relay. Client-side encrypted frames, distinct from pk-speak /remote.",
            "packages/collab-web + packages/collab-relay + coding-agent/src/collab. Images survive because the journal taps pre-externalized entries.",
            &[
                "packages/collab-web",
                "packages/collab-relay",
                "packages/coding-agent/src/collab",
            ],
            vec![
                child("K1", "Relay", 1, "Cloudflare collab-relay"),
                child("K2", "Web", 1, "browser guest"),
            ],
            Box3::new(-18.0, -8.0, 0.0, 5.0, 4.0, 2.8),
            vec![Box3::new(-17.4, -7.4, 2.8, 1.4, 1.2, 1.0)],
        ),
        // ── THE LIVING PROCESS (left-center river) ───────────────────────
        node(
            "session",
            'S',
            "AgentSession",
            Section::Process,
            "Host policy before the core loop: slash commands, templates, magic keywords, task contracts, vision companions, steer vs follow-up.",
            "packages/coding-agent/src/session/agent-session.ts (~14.5k). Also owns compaction, TTSR, retry fallback, ACP permission gate.",
            &["packages/coding-agent/src/session/agent-session.ts"],
            vec![
                child("S1", "prompt()", 1, "host policy then Agent.prompt"),
                child("S2", "steer", 1, "mid-run queue, not a new loop"),
                child("S3", "ACP gate", 4, "bash/edit/delete/move"),
            ],
            Box3::new(-8.0, 8.0, 0.0, 5.4, 4.2, 3.6),
            vec![
                Box3::new(-7.2, 8.6, 3.6, 1.8, 1.5, 1.3),
                Box3::new(-5.2, 9.0, 3.6, 1.2, 1.1, 0.8),
            ],
        ),
        node(
            "loop",
            'L',
            "runLoopBody",
            Section::Process,
            "The load-bearing turn. Model → tools → steer → follow-up. Outer follow-up loop, inner tool loop, pause_turn re-sample (max 8).",
            "packages/agent/src/agent-loop.ts. Hard caps: deadline, maxModelRequestsPerRun, abort. Steering is not drained on user abort.",
            &["packages/agent/src/agent-loop.ts", "packages/agent/src/agent.ts"],
            vec![
                child("L1", "stream", 1, "streamAssistantResponse"),
                child("L2", "tools", 1, "executeToolCalls"),
                child("L3", "steer", 1, "drain mid-work asides"),
            ],
            Box3::new(-8.0, 1.5, 0.0, 5.4, 4.4, 4.0),
            vec![Box3::new(-7.0, 2.2, 4.0, 2.0, 1.6, 1.4)],
        ),
        node(
            "stream",
            'R',
            "streamDispatch",
            Section::Process,
            "One switch on model.api. Custom registry, GitLab Duo, Vertex/Bedrock, then Anthropic/OpenAI/Azure/Google/Ollama/Cursor/Devin.",
            "packages/ai/src/stream.ts. streamSimple adds auth retry, mapOptionsForApi, thinking budgets, tool-choice translation.",
            &["packages/ai/src/stream.ts"],
            vec![
                child("R1", "streamSimple", 1, "auth + option mapping"),
                child("R2", "dialects", 0, "{providers} lazy provider adapters"),
            ],
            Box3::new(-8.0, -5.0, 0.0, 5.4, 4.0, 2.8),
            vec![],
        ),
        node(
            "tools",
            'T',
            "createTools",
            Section::Process,
            "BUILTIN_TOOLS factory. Essential always-on: read, bash, edit, write, todo, glob, eval. Everything else is discoverable.",
            "packages/coding-agent/src/tools/index.ts. Hidden: yield/resolve/report_*/goal. Gated: github, inspect_image, memory, learn.",
            &["packages/coding-agent/src/tools"],
            vec![
                child("T1", "Essential", 7, "read bash edit write todo glob eval"),
                child("T2", "Discoverable", 0, "{tools} tool modules"),
                child("T3", "Hidden", 5, "yield resolve report goal"),
            ],
            Box3::new(-8.0, -11.0, 0.0, 5.4, 4.2, 3.2),
            vec![Box3::new(-7.3, -10.4, 3.2, 1.5, 1.3, 1.0)],
        ),
        // ── THE SYSTEM (center stack) ────────────────────────────────────
        node(
            "host",
            'H',
            "coding-agent",
            Section::System,
            "Composition root. CLI, SDK createAgentSession, modes, plugins, settings, AuthStorage, ModelRegistry.",
            "packages/coding-agent/src/{cli,main,sdk}.ts. runRootCommand is a timed sequential boot with a 10s watchdog.",
            &[
                "packages/coding-agent/src/cli.ts",
                "packages/coding-agent/src/main.ts",
                "packages/coding-agent/src/sdk.ts",
            ],
            vec![
                child("H1", "cli.ts", 1, "Bun.main + profile + workers"),
                child("H2", "main.ts", 1, "runRootCommand boot"),
                child("H3", "sdk.ts", 1, "createAgentSession"),
            ],
            Box3::new(2.0, 8.0, 0.0, 5.2, 4.2, 3.4),
            vec![Box3::new(2.8, 8.6, 3.4, 1.6, 1.4, 1.1)],
        ),
        node(
            "core",
            'A',
            "agent-core",
            Section::System,
            "Agent state machine + queues. Default streamFn is streamSimple. Events: agent/turn/message/tool_* .",
            "packages/agent/src/{agent,agent-loop,types}.ts. convertToLlm drops UI-only messages at the provider seam.",
            &["packages/agent/src"],
            vec![
                child("A1", "Agent", 1, "prompt / continue / steer"),
                child("A2", "Context", 1, "systemPrompt + messages + tools"),
            ],
            Box3::new(2.0, 2.0, 0.0, 5.2, 4.0, 3.0),
            vec![],
        ),
        node(
            "ai",
            'I',
            "pi-ai",
            Section::System,
            "Provider adapters, auth storage, retries, dialects. Public seam: stream / streamSimple / complete.",
            "packages/ai/src. coding-agent must import catalog values from pi-catalog, never pi-ai (type-only Model/Api allowed).",
            &["packages/ai/src"],
            vec![
                child("I1", "Auth", 1, "AuthStorage + retry"),
                child("I2", "Providers", 0, "{providers} registered APIs"),
            ],
            Box3::new(2.0, -4.0, 0.0, 5.2, 4.0, 2.6),
            vec![],
        ),
        node(
            "catalog",
            'C',
            "pi-catalog",
            Section::System,
            "Identity source. 59 providers, ~4k model entries. getBundledModel, discovery, model-manager.",
            "packages/catalog/src + models.yml compiled to models.json. Version lockstep 16.4.1.",
            &["packages/catalog/src"],
            vec![
                child("C1", "models.yml", 1, "source of truth"),
                child("C2", "Providers", 0, "{catalog_providers} provider ids"),
            ],
            Box3::new(2.0, -10.0, 0.0, 5.2, 4.0, 2.8),
            vec![Box3::new(2.7, -9.4, 2.8, 1.4, 1.2, 0.9)],
        ),
        node(
            "natives",
            'E',
            "pi-natives",
            Section::System,
            "Rust N-API leaf. grep/glob/ast/block/shell/pty/iso/text. JS owns policy; Rust owns the scan.",
            "crates/pi-natives/src/lib.rs + packages/natives. Supporting: pi-ast, pi-shell (brush), pi-iso.",
            &["crates/pi-natives/src", "packages/natives"],
            vec![
                child("E1", "search", 4, "grep glob ast block"),
                child("E2", "exec", 4, "shell pty ps iso"),
                child("E3", "system", 7, "clipboard keys sixel …"),
            ],
            Box3::new(8.5, -10.0, 0.0, 4.6, 4.0, 3.0),
            vec![],
        ),
        // ── THE MEMORY (right-rear) ──────────────────────────────────────
        node(
            "journal",
            'J',
            "Session JSONL",
            Section::Memory,
            "Crash-safe append journal. Header + SessionEntry tree via (id, parentId). Mutable leaf = active branch.",
            "packages/coding-agent/src/session/session-manager.ts + session-entries.ts. Temp+rename rewrite. Blobs externalize.",
            &[
                "packages/coding-agent/src/session/session-manager.ts",
                "packages/coding-agent/src/session/session-entries.ts",
            ],
            vec![
                child("J1", "Header", 1, "SessionHeader"),
                child("J2", "Entries", 12, "message/compaction/branch/…"),
            ],
            Box3::new(13.0, 10.0, 0.0, 5.0, 4.0, 3.0),
            vec![Box3::new(13.8, 10.6, 3.0, 1.5, 1.3, 1.1)],
        ),
        node(
            "compact",
            'P',
            "Compaction",
            Section::Memory,
            "Context reduction before the next model call. compact / prune / shake. Hysteresis band 0.8 after maintenance.",
            "packages/agent/src/compaction + snapcompact + AgentSession prune cache (8k warm suffix, 90min idle flush).",
            &[
                "packages/agent/src/compaction",
                "packages/snapcompact/src",
            ],
            vec![
                child("P1", "compact", 1, "agent-core summarizer"),
                child("P2", "prune", 1, "consumed-observation mask"),
                child("P3", "snap", 1, "vision bitmap compressor"),
            ],
            Box3::new(13.0, 4.0, 0.0, 5.0, 4.0, 2.8),
            vec![],
        ),
        node(
            "memory",
            'N',
            "Memory Backends",
            Section::Memory,
            "retain / recall / reflect / memory_edit. resolveMemoryBackend picks hindsight | mnemopi | local | off.",
            "packages/coding-agent/src/memory-backend + hindsight + mnemopi. Two+ adapters = a real seam.",
            &[
                "packages/coding-agent/src/memory-backend",
                "packages/coding-agent/src/hindsight",
                "packages/mnemopi/src",
            ],
            vec![
                child("N1", "hindsight", 1, "conversation memory"),
                child("N2", "mnemopi", 1, "SQLite + embeddings"),
                child("N3", "local", 1, "file-backed fallback"),
            ],
            Box3::new(13.0, -2.0, 0.0, 5.0, 4.0, 2.6),
            vec![],
        ),
        node(
            "urls",
            'U',
            "Internal URLs",
            Section::Memory,
            "Process-global InternalUrlRouter. agent:// artifact:// history:// issue:// skill:// memory:// vault:// …",
            "packages/coding-agent/src/internal-urls. Same FS tools, different handlers. local:// persists across turns.",
            &["packages/coding-agent/src/internal-urls"],
            vec![
                child("U1", "Schemes", 14, "agent artifact history issue …"),
                child("U2", "Router", 1, "InternalUrlRouter"),
            ],
            Box3::new(13.0, -8.0, 0.0, 5.0, 4.0, 2.4),
            vec![],
        ),
        // ── THE EVOLUTION LOOP (front-right) ─────────────────────────────
        node(
            "task",
            'X',
            "Task Spawn",
            Section::Evolution,
            "Recursive createAgentSession. Parallel tasks[], IRC, worktree/iso, recovery capsules, write-scope ownership.",
            "packages/coding-agent/src/task. Discover agents → validate spawn contract → TaskExecutor.",
            &["packages/coding-agent/src/task"],
            vec![
                child("X1", "Executor", 1, "TaskExecutor"),
                child("X2", "IRC", 1, "deliverIrcMessage"),
                child("X3", "Iso", 1, "worktree / pi-iso"),
            ],
            Box3::new(8.0, -16.0, 0.0, 5.0, 4.2, 3.2),
            vec![Box3::new(8.8, -15.3, 3.2, 1.5, 1.3, 1.1)],
        ),
        node(
            "discovery",
            'D',
            "Discovery",
            Section::Evolution,
            "Import-time defineCapability + registerProvider. Walks cwd → repo → home. Priority-dedupes, honors disabledExtensions.",
            "packages/coding-agent/src/{discovery,capability,extensibility}. Providers: builtin, Claude, Cursor, Codex, Cline, VS Code, Windsurf, OpenCode, GitHub, omp-plugins.",
            &[
                "packages/coding-agent/src/discovery",
                "packages/coding-agent/src/capability",
                "packages/coding-agent/src/extensibility",
            ],
            vec![
                child("D1", "Capabilities", 0, "{caps} registered providers"),
                child("D2", "Extensions", 1, "plugin-root preload"),
            ],
            Box3::new(1.5, -16.0, 0.0, 5.0, 4.0, 2.6),
            vec![],
        ),
        node(
            "skills",
            'G',
            "Skills / TTSR",
            Section::Evolution,
            "Skill listing in the system prompt. TTSR stream-rule injection after matched tool results. learn / manage_skill tools.",
            "packages/coding-agent/src/system-prompt.ts + ttsr. Prompt: static .md (Handlebars) + tools + AGENTS.md + skills.",
            &[
                "packages/coding-agent/src/system-prompt.ts",
                "packages/coding-agent/src/skills",
            ],
            vec![
                child("G1", "Prompt", 1, "buildSystemPrompt"),
                child("G2", "TTSR", 1, "rule_violation reminders"),
            ],
            Box3::new(-5.0, -16.0, 0.0, 5.0, 4.0, 2.4),
            vec![],
        ),
        // ── THE INTERFACE (front / top of iso) ───────────────────────────
        node(
            "tui",
            'V',
            "pi-tui",
            Section::Interface,
            "Message-agnostic differential renderer. stdin → focus → Component.render(width) → append-only native scrollback.",
            "packages/tui/src. Overlay/editor semantics stay in coding-agent InteractiveMode + EventController.",
            &["packages/tui/src"],
            vec![
                child("V1", "TUI", 1, "append-only commit ledger"),
                child("V2", "Components", 0, "{tui} widget files"),
            ],
            Box3::new(-11.0, 16.0, 0.0, 5.2, 4.0, 2.8),
            vec![],
        ),
        node(
            "modes",
            'O',
            "Runtimes",
            Section::Interface,
            "Interactive, print, ACP, RPC. Protocol modes own stdin. Piped stdin in text mode auto-selects print.",
            "packages/coding-agent/src/modes + main.ts runRootCommand handoff. robomp talks RPC.",
            &["packages/coding-agent/src/modes"],
            vec![
                child("O1", "interactive", 1, "TUI EventController"),
                child("O2", "print", 1, "headless stdout"),
                child("O3", "acp / rpc", 2, "editor + robomp"),
            ],
            Box3::new(-4.5, 16.0, 0.0, 5.2, 4.0, 2.6),
            vec![],
        ),
        node(
            "cli",
            'Q',
            "CLI",
            Section::Interface,
            "oh-my-pk / omp / ompk. Profile resolved before pi-utils/env. Hidden __omp_worker_* re-enters the same file.",
            "packages/coding-agent/src/cli.ts + cli-commands.ts via pi-utils/cli. Unknown argv becomes launch.",
            &["packages/coding-agent/src/cli.ts", "packages/utils/src"],
            vec![
                child("Q1", "launch", 1, "runRootCommand"),
                child("Q2", "workers", 7, "tiny-inference / eval / stt …"),
            ],
            Box3::new(2.0, 16.0, 0.0, 5.0, 4.0, 2.4),
            vec![],
        ),
        node(
            "python",
            'Y',
            "Satellites",
            Section::Interface,
            "robomp (GitHub triage via omp --mode rpc), omp-rpc client, fugu eval/fusion harness.",
            "python/robomp, python/omp-rpc, python/fugu. PAT lives only in gh-proxy. Not on the hot path.",
            &["python/robomp", "python/omp-rpc", "python/fugu"],
            vec![
                child("Y1", "robomp", 1, "webhook → worktree → rpc"),
                child("Y2", "fugu", 1, "proposer / verifier"),
            ],
            Box3::new(8.5, 16.0, 0.0, 4.8, 4.0, 2.2),
            vec![],
        ),
    ];

    let edges = vec![
        edge("providers", "stream", "tokens", EdgeKind::Data),
        edge("catalog", "stream", "identity", EdgeKind::Control),
        edge("catalog", "ai", "models", EdgeKind::Control),
        edge("stream", "loop", "assistant", EdgeKind::Data),
        edge("loop", "tools", "tool_use", EdgeKind::Control),
        edge("tools", "natives", "scan/exec", EdgeKind::Control),
        edge("natives", "tools", "results", EdgeKind::Data),
        edge("tools", "workspace", "read/edit", EdgeKind::Data),
        edge("tools", "mcp", "mcp__", EdgeKind::Control),
        edge("mcp", "tools", "tool_result", EdgeKind::Data),
        edge("tools", "urls", "scheme", EdgeKind::Data),
        edge("session", "loop", "prompt", EdgeKind::Control),
        edge("host", "session", "compose", EdgeKind::Control),
        edge("host", "cli", "boot", EdgeKind::Control),
        edge("cli", "modes", "handoff", EdgeKind::Control),
        edge("modes", "tui", "frames", EdgeKind::Data),
        edge("tui", "session", "events", EdgeKind::Feedback),
        edge("loop", "journal", "entries", EdgeKind::Data),
        edge("journal", "compact", "overflow", EdgeKind::Feedback),
        edge("compact", "loop", "headroom", EdgeKind::Feedback),
        edge("memory", "session", "recall", EdgeKind::Data),
        edge("session", "memory", "retain", EdgeKind::Data),
        edge("loop", "task", "spawn", EdgeKind::Control),
        edge("task", "session", "child", EdgeKind::Control),
        edge("discovery", "host", "caps", EdgeKind::Control),
        edge("skills", "session", "prompt", EdgeKind::Data),
        edge("session", "stream", "system", EdgeKind::Data),
        edge("collab-world", "session", "frames", EdgeKind::Data),
        edge("python", "modes", "rpc", EdgeKind::Control),
        edge("ai", "stream", "dispatch", EdgeKind::Control),
        edge("core", "loop", "state", EdgeKind::Control),
        edge("urls", "tools", "resolve", EdgeKind::Data),
    ];

    Graph {
        metrics: Metrics {
            project_name: "oh-my-pk".into(),
            version: "16.4.1".into(),
            ..Metrics::default()
        },
        nodes,
        edges,
        unmapped: Vec::new(),
    }
}

fn node(
    id: &str,
    code: char,
    name: &str,
    section: Section,
    what: &str,
    how: &str,
    paths: &[&str],
    children: Vec<Child>,
    r#box: Box3,
    stacks: Vec<Box3>,
) -> Node {
    Node {
        id: id.into(),
        code,
        name: name.into(),
        section,
        count: 0,
        count_label: String::new(),
        what: what.into(),
        how: how.into(),
        paths: paths.iter().map(|p| (*p).to_string()).collect(),
        children,
        r#box,
        stacks,
    }
}

fn child(code: &str, name: &str, count: u32, note: &str) -> Child {
    Child {
        code: code.into(),
        name: name.into(),
        count,
        note: note.into(),
    }
}

fn edge(from: &str, to: &str, label: &str, kind: EdgeKind) -> Edge {
    Edge {
        from: from.into(),
        to: to.into(),
        label: label.into(),
        kind,
        payloads: Vec::new(),
    }
}
