#!/bin/sh
# install.sh — install the omp coding agent on the target server.
#
# Part of the omp deployment kit. Installs from the files shipped next to
# this script (offline; no network required). Verifies the binary checksum
# recorded in MANIFEST.txt before touching the system.
#
# Usage:
#   sudo ./install.sh                    # standard install (binary + completions)
#   sudo ./install.sh --with-broker      # also install omp auth-broker systemd service
#   ./install.sh --destroot /tmp/sandbox # stage under a directory (testing/image builds)
#
# Flags:
#   --prefix DIR        install location prefix (default /usr/local; binary -> PREFIX/bin/omp)
#   --destroot DIR      prepend DIR to every absolute path (for staging; implies no systemctl)
#   --with-broker       create the omp-broker system user and enable omp-auth-broker.service
#   --no-completions    skip shell completion installation
#   --rollback          restore the previous binary saved by an earlier install
#
# Idempotent: safe to re-run for upgrades; the existing binary is kept as
# omp.prev for --rollback.

set -eu

PREFIX="/usr/local"
DESTROOT=""
WITH_BROKER=0
NO_COMPLETIONS=0
ROLLBACK=0

while [ $# -gt 0 ]; do
	case "$1" in
	--prefix)
		PREFIX="${2:?missing value for --prefix}"
		shift 2
		;;
	--destroot)
		DESTROOT="${2:?missing value for --destroot}"
		shift 2
		;;
	--with-broker)
		WITH_BROKER=1
		shift
		;;
	--no-completions)
		NO_COMPLETIONS=1
		shift
		;;
	--rollback)
		ROLLBACK=1
		shift
		;;
	--help | -h)
		sed -n '2,25p' "$0" | sed 's/^# \{0,1\}//'
		exit 0
		;;
	*)
		echo "unknown option: $1 (see --help)" >&2
		exit 2
		;;
	esac
done

KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
OMP_BIN="$DESTROOT$PREFIX/bin/omp"
MANIFEST="$KIT_DIR/MANIFEST.txt"

log() { echo "==> $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

[ -f "$MANIFEST" ] || die "MANIFEST.txt not found next to install.sh — incomplete kit?"
[ -f "$KIT_DIR/bin/omp" ] || die "bin/omp not found next to install.sh — incomplete kit?"

# --- privileges -----------------------------------------------------------------
if [ "$(id -u)" -ne 0 ] && [ -z "$DESTROOT" ]; then
	die "must run as root (sudo) unless --destroot is used for staging"
fi

# --- verify shipped binary against the manifest checksum ------------------------
EXPECTED="$(awk '$1 == "binary-sha256:" { print $2 }' "$MANIFEST")"
[ -n "$EXPECTED" ] || die "MANIFEST.txt has no binary-sha256 entry"
ACTUAL="$(sha256sum "$KIT_DIR/bin/omp" | awk '{print $1}')"
[ "$ACTUAL" = "$EXPECTED" ] ||
	die "checksum mismatch: kit corrupted (expected $EXPECTED, got $ACTUAL)"
log "checksum verified: $ACTUAL"

# --- rollback --------------------------------------------------------------------
if [ "$ROLLBACK" -eq 1 ]; then
	[ -f "$OMP_BIN.prev" ] || die "no previous binary at $OMP_BIN.prev"
	cp "$OMP_BIN.prev" "$OMP_BIN.new" && mv "$OMP_BIN.new" "$OMP_BIN"
	log "rollback complete: restored previous binary"
	if [ "$NO_COMPLETIONS" -ne 1 ]; then
		"$OMP_BIN" completions bash >"$DESTROOT/etc/profile.d/omp-completions.sh" 2>/dev/null || true
	fi
	log "run '$(basename "$OMP_BIN") --version' to confirm"
	exit 0
fi

# --- install binary ---------------------------------------------------------------
mkdir -p "$DESTROOT$PREFIX/bin"
if [ -f "$OMP_BIN" ]; then
	log "backing up existing binary -> omp.prev"
	cp -f "$OMP_BIN" "$OMP_BIN.prev"
fi
cp "$KIT_DIR/bin/omp" "$OMP_BIN.new"
mv "$OMP_BIN.new" "$OMP_BIN" # atomic on same filesystem
chmod 0755 "$OMP_BIN"
log "installed $OMP_BIN"

# --- shell completions (generated by the installed binary, so they match) --------
if [ "$NO_COMPLETIONS" -ne 1 ]; then
	mkdir -p "$DESTROOT/etc/profile.d"
	"$OMP_BIN" completions bash >"$DESTROOT/etc/profile.d/omp-completions.sh"
	log "installed bash completions -> /etc/profile.d/omp-completions.sh"

	ZSH_DIR="$DESTROOT$PREFIX/share/zsh/site-functions"
	if [ -d "$ZSH_DIR" ]; then
		"$OMP_BIN" completions zsh >"$ZSH_DIR/_omp"
		log "installed zsh completions -> $ZSH_DIR/_omp"
	else
		log "skip zsh completions ($ZSH_DIR not present; is zsh installed?)"
	fi

	FISH_DIR="$DESTROOT/etc/fish/completions"
	if [ -d "$FISH_DIR" ]; then
		"$OMP_BIN" completions fish >"$FISH_DIR/omp.fish"
		log "installed fish completions -> $FISH_DIR/omp.fish"
	else
		log "skip fish completions ($FISH_DIR not present; is fish installed?)"
	fi

	# Non-default prefix: make the binary visible on PATH for login shells.
	if [ "$PREFIX" != "/usr/local" ] && [ -z "$DESTROOT" ]; then
		{
			echo '# Added by omp deployment kit'
			echo "case \":\$PATH:\" in *\":$PREFIX/bin:\"*) ;; *) PATH=\"$PREFIX/bin:\$PATH\" ;; esac"
		} >"$DESTROOT/etc/profile.d/omp-path.sh"
		log "installed PATH shim -> /etc/profile.d/omp-path.sh (prefix $PREFIX)"
	fi
fi

# --- optional: auth-broker systemd service ----------------------------------------
if [ "$WITH_BROKER" -eq 1 ]; then
	if [ -n "$DESTROOT" ]; then
		install -m 0644 "$KIT_DIR/systemd/omp-auth-broker.service" \
			"$DESTROOT/etc/systemd/system/omp-auth-broker.service"
		log "staged unit -> $DESTROOT/etc/systemd/system/ (systemctl skipped under --destroot)"
	else
		NOLOGIN="/usr/sbin/nologin"
		[ -x "$NOLOGIN" ] || NOLOGIN="/sbin/nologin"
		if ! id omp-broker >/dev/null 2>&1; then
			useradd --system --create-home --shell "$NOLOGIN" omp-broker
			log "created system user omp-broker (home: $(getent passwd omp-broker | cut -d: -f6))"
		fi
		install -m 0644 "$KIT_DIR/systemd/omp-auth-broker.service" \
			"$DESTROOT/etc/systemd/system/omp-auth-broker.service"
		if command -v systemctl >/dev/null 2>&1; then
			systemctl daemon-reload
			systemctl enable --now omp-auth-broker.service
			log "omp-auth-broker.service enabled and started"
		else
			log "systemctl not available — unit installed but not started"
		fi
	fi
fi

# --- summary ----------------------------------------------------------------------
log "install complete"
echo ""
sed 's/^/    /' "$MANIFEST"
echo ""
echo "Next steps:"
if [ "$WITH_BROKER" -eq 1 ]; then
	echo "  1. ./verify.sh --with-broker   # health check"
else
	echo "  1. ./verify.sh                 # health check"
fi
echo "  2. Per-user setup: see README.md section 'Per-user configuration'"
