import type { RouterConfig } from "./types.js";

export const DEFAULT_CONFIG: RouterConfig = {
	version: 1,
	objectives: {
		quality: 0.45,
		latency: 0.2,
		cost: 0.2,
		safety: 0.15,
	},
	models: {
		fast: {
			id: "fast",
			selector: "pi/smol",
			fallbackSelectors: ["smol", "default"],
			label: "Small fast model",
			quality: 0.58,
			latencyMsP95: 1200,
			costPerMillionTokens: 0.2,
			safety: 0.72,
			contextWindow: 64_000,
			maxOutputTokens: 8_000,
			capabilities: ["text", "json", "fast", "cheap"],
		},
		balanced: {
			id: "balanced",
			selector: "default",
			fallbackSelectors: ["pi/default", "pi/slow"],
			label: "Default balanced model",
			quality: 0.76,
			latencyMsP95: 2600,
			costPerMillionTokens: 1.0,
			safety: 0.82,
			contextWindow: 128_000,
			maxOutputTokens: 16_000,
			capabilities: ["text", "json", "code", "tools", "reasoning"],
		},
		quality: {
			id: "quality",
			selector: "pi/slow",
			fallbackSelectors: ["slow", "default"],
			label: "Highest quality/reasoning model",
			quality: 0.92,
			latencyMsP95: 6200,
			costPerMillionTokens: 4.0,
			safety: 0.9,
			contextWindow: 200_000,
			maxOutputTokens: 32_000,
			capabilities: ["text", "json", "code", "tools", "reasoning", "safe", "long-context"],
		},
		coding: {
			id: "coding",
			selector: "pi/slow",
			fallbackSelectors: ["default"],
			label: "Coding-capable model",
			quality: 0.88,
			latencyMsP95: 5200,
			costPerMillionTokens: 3.0,
			safety: 0.84,
			contextWindow: 180_000,
			maxOutputTokens: 32_000,
			capabilities: ["text", "json", "code", "tools", "reasoning", "long-context"],
		},
		structured: {
			id: "structured",
			selector: "default",
			fallbackSelectors: ["pi/slow"],
			label: "Structured-output model",
			quality: 0.8,
			latencyMsP95: 2800,
			costPerMillionTokens: 1.2,
			safety: 0.82,
			contextWindow: 128_000,
			maxOutputTokens: 16_000,
			capabilities: ["text", "json", "tools"],
		},
		long_context: {
			id: "long_context",
			selector: "pi/slow",
			fallbackSelectors: ["default"],
			label: "Long-context model",
			quality: 0.86,
			latencyMsP95: 5800,
			costPerMillionTokens: 3.25,
			safety: 0.86,
			contextWindow: 400_000,
			maxOutputTokens: 32_000,
			capabilities: ["text", "json", "long-context", "reasoning"],
		},
		safe: {
			id: "safe",
			selector: "pi/slow",
			fallbackSelectors: ["default"],
			label: "Safety-robust model",
			quality: 0.84,
			latencyMsP95: 4800,
			costPerMillionTokens: 2.5,
			safety: 0.96,
			contextWindow: 200_000,
			maxOutputTokens: 16_000,
			capabilities: ["text", "json", "tools", "reasoning", "safe"],
		},
	},
	rules: [
		{
			name: "safety-sensitive",
			priority: 100,
			description: "Route sensitive or policy-risky work to the safest profile.",
			when: { minSafetySensitivity: 0.45 },
			route: { model: "safe", fallback: ["quality", "balanced"], force: true, reason: "safety-sensitive request" },
		},
		{
			name: "multimodal",
			priority: 95,
			description: "Prefer models configured for multimodal input.",
			when: { hasMultimodalInput: true },
			route: { model: "quality", fallback: ["balanced"], reason: "multimodal input" },
		},
		{
			name: "high-complexity-coding",
			priority: 90,
			description: "Escalate difficult coding and architecture tasks.",
			when: { taskType: "coding", minReasoningComplexity: 0.45 },
			route: { model: "coding", fallback: ["quality", "balanced"], force: true, reason: "high-complexity coding" },
		},
		{
			name: "long-context",
			priority: 85,
			description: "Use a long-context profile for large prompts or many attachments.",
			when: { minTokens: 48_000 },
			route: { model: "long_context", fallback: ["quality", "balanced"], reason: "large context" },
		},
		{
			name: "structured-output",
			priority: 70,
			description: "Prefer JSON/schema-reliable models for extraction and structured outputs.",
			when: { hasJsonRequirement: true },
			route: { model: "structured", fallback: ["quality", "balanced"], reason: "structured output required" },
		},
		{
			name: "simple-translation-fast",
			priority: 60,
			description: "Use fast/cheap profile for simple translation.",
			when: { taskType: "translation", maxTokens: 6_000, preference: ["speed", "cost", "balanced"] },
			route: { model: "fast", fallback: ["balanced"], reason: "simple translation" },
		},
		{
			name: "speed-preference",
			priority: 50,
			description: "Respect explicit speed preference for non-complex work.",
			when: { preference: "speed", maxTokens: 12_000 },
			route: { model: "fast", fallback: ["balanced"], reason: "user prefers speed" },
		},
		{
			name: "quality-preference",
			priority: 50,
			description: "Respect explicit quality preference.",
			when: { preference: "quality" },
			route: { model: "quality", fallback: ["balanced"], reason: "user prefers quality" },
		},
	],
	learned: {
		enabled: false,
		intercept: 0,
		modelWeights: {},
		globalWeights: {},
		minConfidenceToOverride: 0.18,
	},
	telemetry: {
		enabled: true,
		path: ".llm-router/telemetry.jsonl",
		sampleRate: 1,
	},
	toolCapture: {
		enabled: true,
		path: ".llm-router/tool-use.jsonl",
		sampleRate: 1,
		captureArgs: "redacted",
		captureResults: "summary",
		maxPayloadChars: 2_000,
		maxSummaryChars: 900,
		contextBudgetTokens: 400,
		emitToTelemetry: false,
		includeTrainingHints: true,
		ignoredToolNames: ["router_capture_tool_use", "router_export_tool_training"],
		redactKeys: [
			"api_key",
			"apikey",
			"authorization",
			"cookie",
			"password",
			"secret",
			"token",
			"access_token",
			"refresh_token",
			"private_key",
			"client_secret",
		],
		redactPatterns: [
			"Bearer\\s+[A-Za-z0-9._~+/=-]+",
			"sk-[A-Za-z0-9]{16,}",
			"(api[_-]?key|token|secret|password)\\s*[:=]\\s*[^\\s,}]+",
		],
	},
	extension: {
		mode: "recommend",
		routeOnInput: true,
		notifyOnInput: false,
		exposeTools: true,
		exposeCommand: true,
	},
	validation: {
		unsafePatternHints: [],
		maxRepairAttempts: 1,
	},
};

export function cloneDefaultConfig(): RouterConfig {
	return JSON.parse(JSON.stringify(DEFAULT_CONFIG)) as RouterConfig;
}
